name:                dietpdf
version:             0.1.0.0
github:              "zigazou/dietpdf"
license:             BSD3
author:              "Frédéric BISSON"
maintainer:          "zigazou@protonmail.com"
copyright:           "2022 Frédéric BISSON"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/zigazou/dietpdf#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -fwrite-ide-info
- -funbox-strict-fields
- -hiedir=.hie
- -Weverything
- -Wno-missing-safe-haskell-mode
- -Wno-implicit-prelude
- -Wno-prepositive-qualified-module
- -Wno-all-missed-specialisations
- -Wno-unsafe
- -Wno-safe

library:
  source-dirs: src
  default-extensions:
  - StrictData
  - BangPatterns
  - Strict
  - DerivingStrategies
  - OverloadedStrings
  ghc-options:
  - -O2
  - -funfolding-use-threshold=16
  - -optc-O3
  - -optc-ffast-math
  - -flate-dmd-anal
  - -fmax-simplifier-iterations=6
  - -flate-specialise
  - -fstatic-argument-transformation
  dependencies:
  - bytestring
  - binary
  - binary-parsers
  - ordered-containers
  - containers
  - mtl
  - monad-loops
  - utf8-string
  - split
  - sort
  - zlib
  - hopfli
  - text
  - formatting
  - xml
  - transformers
  - stringsearch
  - double-conversion
  - fmt
  - cryptonite

executables:
  dietpdf:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
    - StrictData
    - Strict
    - BangPatterns
    - DerivingStrategies
    - OverloadedStrings
    ghc-options:
    - -O2
    - -funfolding-use-threshold=16
    - -optc-O3
    - -optc-ffast-math
    - -flate-dmd-anal
    - -fmax-simplifier-iterations=6
    - -flate-specialise
    - -fstatic-argument-transformation
    dependencies:
    - bytestring
    - optparse-applicative
    - dietpdf
    - text
    - formatting
    - transformers
    - mtl
    - pretty-hex
    - containers

tests:
  dietpdf-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - dietpdf
    - hspec
    - QuickCheck
    - bytestring
    - containers
    - binary-parsers
    - text
    - transformers
    - zlib
    - extra
    - mtl