name:                dietpdf
version:             1.1.4.0
github:              "zigazou/dietpdf"
license:             BSD3
author:              "Frédéric BISSON"
maintainer:          "zigazou@protonmail.com"
copyright:           "2026 Frédéric BISSON"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Please see the README on GitHub at <https://github.com/zigazou/dietpdf#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -fwrite-ide-info
- -funbox-strict-fields
- -fspecialise-aggressively
- -fexpose-all-unfoldings
- -fllvm
- -hiedir=.hie
- -Weverything
- -Wno-missing-safe-haskell-mode
- -Wno-implicit-prelude
- -Wno-missed-specialisations
- -Wno-all-missed-specialisations
- -Wno-unsafe
- -Wno-safe
- -Wno-redundant-bang-patterns
- -j
- -threaded
library:
  source-dirs: src
  default-extensions:
  - StrictData
  - BangPatterns
  - Strict
  - DerivingStrategies
  - OverloadedStrings
  - InstanceSigs
  - GADTs
  - FlexibleInstances
  - LambdaCase
  - FlexibleContexts
  - MultiWayIf
  - TupleSections
  - StandaloneKindSignatures
  - ImportQualifiedPost
  - RoleAnnotations
  - NumericUnderscores
  - BinaryLiterals
  - ViewPatterns
  - PatternSynonyms
  ghc-options:
  - -O2
  - -funfolding-use-threshold=16
  - -optc-O3
  - -optc-ffast-math
  - -flate-dmd-anal
  - -fmax-simplifier-iterations=6
  - -flate-specialise
  - -fstatic-argument-transformation
  - -threaded
  dependencies:
  - bytestring
  - binary
  - binary-parsers
  - ordered-containers
  - containers
  - mtl
  - monad-loops
  - utf8-string
  - split
  - zlib
  - hopfli
  - text
  - formatting
  - xml
  - transformers
  - stringsearch
  - double-conversion
  - cryptonite
  - process
  - vector
  - spool
  - temporary
  - async
  - extra
  - base64-bytestring

executables:
  dietpdf:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
    - StrictData
    - Strict
    - BangPatterns
    - DerivingStrategies
    - OverloadedStrings
    - InstanceSigs
    - GADTs
    - FlexibleInstances
    - LambdaCase
    - FlexibleContexts
    - MultiWayIf
    - TupleSections
    - StandaloneKindSignatures  
    - ImportQualifiedPost
    ghc-options:
    - -O2
    - -funfolding-use-threshold=16
    - -optc-O3
    - -optc-ffast-math
    - -flate-dmd-anal
    - -fmax-simplifier-iterations=6
    - -flate-specialise
    - -fstatic-argument-transformation
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - optparse-applicative
    - dietpdf
    - text
    - formatting
    - transformers
    - pretty-hex
    - containers
    - temporary
    - unix
    - filepath
    - mtl

tests:
  dietpdf-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
    - StrictData
    - Strict
    - BangPatterns
    - DerivingStrategies
    - OverloadedStrings
    - InstanceSigs
    - GADTs
    - FlexibleInstances
    - LambdaCase
    - FlexibleContexts
    - MultiWayIf
    - TupleSections
    - StandaloneKindSignatures
    - ImportQualifiedPost
    - NumericUnderscores
    - BinaryLiterals
    ghc-options:
    - -O2
    - -funfolding-use-threshold=16
    - -optc-O3
    - -optc-ffast-math
    - -flate-dmd-anal
    - -fmax-simplifier-iterations=6
    - -flate-specialise
    - -fstatic-argument-transformation
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dietpdf
    - hspec
    - QuickCheck
    - bytestring
    - containers
    - binary-parsers
    - text
    - transformers
    - zlib
    - extra
    - mtl
    - vector
    - xml
    - utf8-string
